# Generated by Django 5.2.7 on 2025-12-16 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the song", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique, URL-friendly version of the song name",
                        max_length=300,
                        unique=True,
                    ),
                ),
                (
                    "song_number",
                    models.PositiveIntegerField(help_text="Track number of the song"),
                ),
                (
                    "singer",
                    models.CharField(help_text="Singer(s) of the song", max_length=150),
                ),
                (
                    "spotify_song",
                    models.URLField(
                        blank=True, help_text="Optional Spotify song link", null=True
                    ),
                ),
                (
                    "spotify_song_poster",
                    models.URLField(
                        blank=True, help_text="Spotify track cover image", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SongDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        help_text="Genre of the song or album", max_length=70
                    ),
                ),
                ("album", models.CharField(help_text="Album name", max_length=50)),
                (
                    "composer",
                    models.CharField(
                        help_text="Composer(s) of the song", max_length=150
                    ),
                ),
                (
                    "spotify_album",
                    models.URLField(
                        blank=True, help_text="Optional Spotify album link", null=True
                    ),
                ),
                (
                    "spotify_album_poster",
                    models.URLField(
                        blank=True, help_text="Spotify album cover image", null=True
                    ),
                ),
                ("release_date", models.DateField(help_text="Official release date")),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="data.song",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Song Details",
            },
        ),
    ]
