# Generated by Django 5.2.7 on 2025-12-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="song_number",
            field=models.PositiveIntegerField(
                blank=True, help_text="Track number of the song", null=True
            ),
        ),
    ]
