# Generated by Django 5.2.7 on 2025-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_song_song_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="composer",
            field=models.CharField(
                blank=True,
                help_text="Composer(s) of the song",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="singer",
            field=models.CharField(
                blank=True, help_text="Singer(s) of the song", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="spotify_song",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="spotify_song_poster",
            field=models.URLField(blank=True, null=True),
        ),
    ]
