# Generated by Django 5.2.7 on 2025-12-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_song_composer_alter_song_singer_alter_song_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={},
        ),
    ]
