# Generated by Django 5.2.7 on 2025-12-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_alter_song_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="song_number",
        ),
        migrations.AddField(
            model_name="song",
            name="track_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Track number of the song (Spotify original)",
                null=True,
            ),
        ),
    ]
