# Generated by Django 5.2.7 on 2025-12-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_remove_song_song_number_song_track_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="composer",
            field=models.CharField(
                blank=True,
                default="No Composer",
                help_text="Composer(s) of the song",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="singer",
            field=models.CharField(
                blank=True,
                default="No Singer",
                help_text="Singer(s) of the song",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="track_number",
            field=models.PositiveIntegerField(
                blank=True,
                default="Track Number Unknown",
                help_text="Track number of the song (Spotify original)",
                null=True,
            ),
        ),
    ]
