# Generated by Django 5.2.7 on 2025-12-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_alter_song_composer_alter_song_singer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="composer",
            field=models.CharField(
                blank=True,
                default="No Composer",
                help_text="Composer(s) of the song",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="singer",
            field=models.CharField(
                blank=True,
                default="No Singer",
                help_text="Singer(s) of the song",
                max_length=150,
            ),
        ),
    ]
