# Generated by Django 5.2.7 on 2025-12-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_alter_song_composer_alter_song_singer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="track_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Track number of the song (Spotify original)",
                null=True,
            ),
        ),
    ]
