# Generated by Django 5.2.7 on 2025-12-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_alter_song_track_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songdetails",
            name="composer",
        ),
        migrations.AddField(
            model_name="songdetails",
            name="album_composer",
            field=models.CharField(
                blank=True,
                default="No Album Composer",
                help_text="Album's Composer Name",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="songdetails",
            name="spotify_song",
            field=models.URLField(blank=True, help_text="Spotify song URL", null=True),
        ),
        migrations.AlterField(
            model_name="songdetails",
            name="album",
            field=models.CharField(blank=True, help_text="Album name", max_length=50),
        ),
        migrations.AlterField(
            model_name="songdetails",
            name="genre",
            field=models.CharField(
                blank=True, help_text="Genre of the song or album", max_length=70
            ),
        ),
        migrations.AlterField(
            model_name="songdetails",
            name="release_date",
            field=models.DateField(
                blank=True, help_text="Official release date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="songdetails",
            name="spotify_album",
            field=models.URLField(blank=True, help_text="Spotify album URL", null=True),
        ),
    ]
