# Generated by Django 5.2.7 on 2025-12-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_remove_songdetails_composer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songdetails",
            name="spotify_song",
        ),
    ]
