# Generated by Django 5.2.7 on 2025-12-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_remove_songdetails_spotify_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songdetails",
            name="album",
            field=models.CharField(blank=True, help_text="Album name", max_length=400),
        ),
    ]
