# Generated by Django 5.2.7 on 2025-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0011_alter_songdetails_album"),
    ]

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the composer", max_length=200
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        help_text="Enter the composer's genre", max_length=150
                    ),
                ),
                ("join_date", models.DateField()),
                ("about", models.TextField(help_text="Enter the bio of the composer")),
                (
                    "recent_release",
                    models.URLField(
                        blank=True,
                        help_text="Spotify URL of the most recent release",
                        null=True,
                    ),
                ),
                (
                    "pic",
                    models.URLField(
                        blank=True, help_text="URL of the composer's picture", null=True
                    ),
                ),
                (
                    "total_album",
                    models.PositiveIntegerField(
                        help_text="Total number of albums by the composer"
                    ),
                ),
                (
                    "single_tracks",
                    models.PositiveIntegerField(
                        help_text="Total number of tracks by the composer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
