# Generated by Django 5.2.7 on 2025-12-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0012_composer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composer",
            name="join_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
